config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  root 'transactions#index'

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params[:transaction]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomerFrontend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-left: 10%; padding-right: 10%">

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div style="float: left; width: 50%;">

  <div style="">
    <h1>Getränke</h1>
    <table>
      <tr>
        <td>Augustiner 0,5l</td>
        <td>1,00€</td>
      </tr>
      <tr>
        <td>Radler 0,5l</td>
        <td>1,00€</td>
      </tr>
      <tr>
        <td>Spezi 0,5l</td>
        <td>1,00€</td>
      </tr>
      <tr>
        <td>Wassser 0,5l</td>
        <td>1,00€</td>
      </tr>
    </table>
  </div>

  <div style="position: absolute; bottom: 0px;margin-bottom: 5%; ">
    <h1>Snacks</h1>
    <table>
      <tr>
        <td>Mars</td>
        <td>0,50€</td>
      </tr>
      <tr>
        <td>Snickers</td>
        <td>0,50€</td>
      </tr>
      <tr>
        <td>Twix</td>
        <td>0,50€</td>
      </tr>
      <tr>
        <td>KitKat</td>
        <td>0,50€</td>
      </tr>
    </table>
  </div>

</div>

<div style="width: 2px; height: 100%; background-color: white; position: absolute; bottom: 0%; left: 45%">
</div>


<div style="float: right; width: 50%;">
  <div>
    <h1>Übersicht</h1>
    <table id="overview">
    </table>
  </div>

  <div style="position: absolute; bottom: 0px;margin-bottom: 5%; width: 100%">
    <div style="width: 100%; height: 2px; background-color: white; position: absolute; left: -5%;">
    </div>
    <h1>Total</h1>
    <strong><p id ="total" style="font-size: 16px">0.00 €</p></strong>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>